# This rule is not used by the project k8s-duckdns itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over duckdns.luitel.dev.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-duckdns
    app.kubernetes.io/managed-by: kustomize
  name: dnsrecord-admin-role
rules:
- apiGroups:
  - duckdns.luitel.dev
  resources:
  - dnsrecords
  verbs:
  - '*'
- apiGroups:
  - duckdns.luitel.dev
  resources:
  - dnsrecords/status
  verbs:
  - get
