---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - delete
  - patch
  - update
- apiGroups:
  - apps
  - batch
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - duckdns.luitel.dev
  resources:
  - dnsrecords
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - duckdns.luitel.dev
  resources:
  - dnsrecords/finalizers
  verbs:
  - update
- apiGroups:
  - duckdns.luitel.dev
  resources:
  - dnsrecords/status
  verbs:
  - get
  - patch
  - update
