apiVersion: duckdns.luitel.dev/v1alpha1
kind: DNSRecord
metadata:
  labels:
    app.kubernetes.io/name: k8s-duckdns
    app.kubernetes.io/managed-by: kustomize
  name: dnsrecord-sample
spec:
  domains:
  - luitel.duckdns.org
  ipv4Address: "99.99.99.99"
  clear: false
  cronJob:
    # This cron expression means every 5 minutes
    # If you want to use a different schedule, you can modify the above line.
    # For example, to run every hour, you could use "0 * * * *".
    # For more information on cron expressions, see https://crontab.guru/
    schedule: "*/5 * * * *"
  secretRef:
    name: duckdns-secret
    namespace: default
    key: token
