apiVersion: v1
kind: Secret
metadata:
  name: duckdns-secret
type: Opaque
data:
  token: <base64_encoded_duckdns_token>
# Note: Replace <base64_encoded_duckdns_token> with the actual base64 encoded value of your DuckDNS token.
# To generate the base64 encoded value, you can use the following command:
# echo -n 'your_duckdns_token' | base64
# Make sure to replace 'your_duckdns_token' with your actual DuckDNS token.
# After generating the base64 encoded value, replace <base64_encoded_duckdns_token> with that value.
# Example:
#   token: dGhpcyBpcyBteSBkdWNrZG5zIHRva2VuCg==
# Ensure that the token is kept secret and not shared publicly.
# This secret is used by the DNSRecord resource to authenticate with DuckDNS.
