apiVersion: duckdns.luitel.dev/v1alpha1
kind: DNSRecord
metadata:
  labels:
    app.kubernetes.io/name: k8s-duckdns
    app.kubernetes.io/managed-by: kustomize
  name: dnsrecord-sample
spec:
  # TODO(user): Add fields here
